### PR TITLE
fixed prefix mask

### PR DESCRIPTION
**Pull request by lintangsutawika**

### CODE REVIEW

**Comment by lintangsutawika** [comment]
```
python evaluation/run_eval.py \
    --dataset_name super_glue \
    --dataset_config_name copa \
    --template_name "best_option" \
    --model_name_or_path ../bloom-ckpt/tr13f-6b3-ml-t0-lmtoks168b-t0toks13b-prefix \
    --output_dir ./prefix/copa-best-option-prefix \
    --prefixlm
```
should result in {'accuracy': 0.63} as oppose to previous 0.53

**Comment by Muennighoff** [comment]
Which transformers version are you using?

I am using [this one](https://github.com/Muennighoff/transformers/blob/prefixlm/src/transformers/models/bloom/modeling_bloom.py), which incorporates the changes from [this PR](https://github.com/huggingface/transformers/pull/18185/files) + allows for prefixlm.

My masks are `-inf` where the model should not pay attention and 0 elsewhere. Note padding is on the left for inputs & right for targets.
Bidirectional input
```python
model_inputs["causal_mask"][0, :, :10, :10]
tensor([[[-inf, -inf, -inf, -inf, -inf, -inf, 0., 0., 0., 0.],
         [-inf, -inf, -inf, -inf, -inf, -inf, 0., 0., 0., 0.],
         [-inf, -inf, -inf, -inf, -inf, -inf, 0., 0., 0., 0.],
         [-inf, -inf, -inf, -inf, -inf, -inf, 0., 0., 0., 0.],
         [-inf, -inf, -inf, -inf, -inf, -inf, 0., 0., 0., 0.],
         [-inf, -inf, -inf, -inf, -inf, -inf, 0., 0., 0., 0.],
         [-inf, -inf, -inf, -inf, -inf, -inf, 0., 0., 0., 0.],
         [-inf, -inf, -inf, -inf, -inf, -inf, 0., 0., 0., 0.],
         [-inf, -inf, -inf, -inf, -inf, -inf, 0., 0., 0., 0.],
         [-inf, -inf, -inf, -inf, -inf, -inf, 0., 0., 0., 0.]]])
```
Causal target
```python
model_inputs["causal_mask"][0, :, -10:, -10:]
tensor([[[0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
         [0., 0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
         [0., 0., 0., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
         [0., 0., 0., 0., -inf, -inf, -inf, -inf, -inf, -inf],
         [0., 0., 0., 0., -inf, -inf, -inf, -inf, -inf, -inf],
         [0., 0., 0., 0., -inf, -inf, -inf, -inf, -inf, -inf],
         [0., 0., 0., 0., -inf, -inf, -inf, -inf, -inf, -inf],
         [0., 0., 0., 0., -inf, -inf, -inf, -inf, -inf, -inf],
         [0., 0., 0., 0., -inf, -inf, -inf, -inf, -inf, -inf],
         [0., 0., 0., 0., -inf, -inf, -inf, -inf, -inf, -inf]]])
```

This is then added to the attention scores [here](https://github.com/Muennighoff/transformers/blob/9a5fc951e008d34469ce671bf17d7831eb2d8b6a/src/transformers/models/bloom/modeling_bloom.py#L305) thus masking out the values we do not want to attend to. The transformation [here](https://github.com/Muennighoff/transformers/blob/9a5fc951e008d34469ce671bf17d7831eb2d8b6a/src/transformers/models/bloom/modeling_bloom.py#L611) does not change the causal mask as it is already applied.


Your masks are first `True` where it should attend and `False` where not. After the combination with the attention mask [here](https://github.com/haileyschoelkopf/transformers/blob/9b3a0d24b52aaa04e10c598ecb93fb0c486716e6/src/transformers/models/bloom/modeling_bloom.py#L597) assuming you use that version, your masks look like the below I think:
```python
out_mask_l[0, :, :10, :10]
tensor([[[-3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38,
          -3.4028e+38,  1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00],
         [-3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38,
          -3.4028e+38,  1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00],
         [-3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38,
          -3.4028e+38,  1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00],
         [-3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38,
          -3.4028e+38,  1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00],
         [-3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38,
          -3.4028e+38,  1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00],
         [-3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38,
          -3.4028e+38,  1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00],
         [-3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38,
          -3.4028e+38,  1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00],
         [-3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38,
          -3.4028e+38,  1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00],
         [-3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38,
          -3.4028e+38,  1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00],
         [-3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38,
          -3.4028e+38,  1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00]]])
```

```python
out_mask_l[0, :, -10:, -10:]
tensor([[[ 1.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00, -3.4028e+38,
          -3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38],
         [ 1.0000e+00,  1.0000e+00,  0.0000e+00,  0.0000e+00, -3.4028e+38,
          -3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38],
         [ 1.0000e+00,  1.0000e+00,  1.0000e+00,  0.0000e+00, -3.4028e+38,
          -3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38],
         [ 1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00, -3.4028e+38,
          -3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38],
         [ 1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00, -3.4028e+38,
          -3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38],
         [ 1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00, -3.4028e+38,
          -3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38],
         [ 1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00, -3.4028e+38,
          -3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38],
         [ 1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00, -3.4028e+38,
          -3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38],
         [ 1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00, -3.4028e+38,
          -3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38],
         [ 1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00, -3.4028e+38,
          -3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38, -3.4028e+38]]])
```
After the [addition](https://github.com/haileyschoelkopf/transformers/blob/9b3a0d24b52aaa04e10c598ecb93fb0c486716e6/src/transformers/models/bloom/modeling_bloom.py#L303) the `-3.4` masks out the padding, but there are some arbitrary `1`s added I think?

I'm probably missing sth here, do you know where I am wrong?

**Comment by lintangsutawika** [comment]
I was basing the implementation from Hailey's PR. I didn't know there was another PR. Looking again at your method, it should be correct.

**Comment by Muennighoff** [comment]
Yes, I forked transformers instead of Hailey's PR because I wanted the changes of [the PR I mentioned](https://github.com/huggingface/transformers/pull/18185/files).
Looking forward to your thoughts!

**Pull request closed without merging**
